from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class GeneratedApp:
    root: Path
    pack_file: Path
    env_example: Path
    config_file: Path


class AppGenerator:
    def __init__(self, destination: str | Path) -> None:
        self.destination = Path(destination)

    def create(self, name: str, *, template: str = "generic", force: bool = False) -> GeneratedApp:
        slug = self._slug(name)
        root = self.destination / slug
        if root.exists() and any(root.iterdir()) and not force:
            raise FileExistsError(root)
        root.mkdir(parents=True, exist_ok=True)
        (root / "packs" / slug).mkdir(parents=True, exist_ok=True)
        (root / "app").mkdir(exist_ok=True)

        pack = {
            "name": slug,
            "display_name": name,
            "template": template,
            "version": "0.1.0",
            "skills": [],
            "mcp": [],
            "agents": [],
            "guardrails": [],
            "knowledge": [],
        }
        pack_file = root / "packs" / slug / "pack.json"
        pack_file.write_text(json.dumps(pack, indent=2) + "\n", encoding="utf-8")

        config_file = root / "continuity.toml"
        config_file.write_text(
            "\n".join(
                [
                    "[app]",
                    f"name = {json.dumps(name)}",
                    'profile = "minimal"',
                    "",
                    "[runtime]",
                    'checkpoint_dir = ".continuity/checkpoints"',
                    'telemetry_path = ".continuity/routes.jsonl"',
                    'memory_path = ".continuity/memory.db"',
                    "",
                    "[[models]]",
                    'id = "dev-echo"',
                    'provider = "dev"',
                    'capabilities = ["text"]',
                    "context_window = 1000000",
                    "quality = 0.1",
                    "reliability = 1.0",
                    "cost_per_million = 0.0",
                    "latency_ms = 0",
                    'privacy = "local"',
                    "max_output_tokens = 4096",
                    "",
                ]
            ),
            encoding="utf-8",
        )

        env_example = root / ".env.example"
        env_example.write_text("# Add app-specific secret names and non-secret configuration here.\n", encoding="utf-8")
        (root / ".gitignore").write_text(
            ".env\n.env.*\n!.env.example\n.secrets/\n.continuity/\n__pycache__/\n.venv/\nnode_modules/\ndist/\n",
            encoding="utf-8",
        )
        (root / "README.md").write_text(
            f"# {name}\n\n"
            f"Generated by ContinuityOS using the `{template}` blueprint.\n\n"
            "## First run\n\n"
            "```bash\n"
            "continuity config-check continuity.toml\n"
            'continuity execute "hello" --config continuity.toml\n'
            "```\n\n"
            f"Customize `packs/{slug}/pack.json` with this app's agents, skills, MCPs, knowledge and guardrails.\n",
            encoding="utf-8",
        )
        return GeneratedApp(root=root, pack_file=pack_file, env_example=env_example, config_file=config_file)

    @staticmethod
    def _slug(name: str) -> str:
        slug = "".join(ch.lower() if ch.isalnum() else "-" for ch in name).strip("-")
        while "--" in slug:
            slug = slug.replace("--", "-")
        if not slug:
            raise ValueError("app name must contain letters or numbers")
        return slug
